name: converter
publish_to: "none"

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../packages/core
  core_storage_base:
    path: ../../packages/core_storage_base
  core_storage_isar:
    path: ../../packages/core_storage_isar
  design_system:
    path: ../../packages/design_system
  icons:
    path: ../../packages/icons
  mobile_ads:
    path: ../../packages/mobile_ads
  mobile_ads_google:
    path: ../../packages/mobile_ads_google
  platform_utils:
    path: ../../packages/platform_utils
  utils:
    path: ../../packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
