name: converter_workspace
publish_to: "none"

workspace:
  - apps/mcu
  - modules/converter
  - packages/core
  - packages/platform_utils
  - packages/utils

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^6.0.0
