name: converter_workspace
publish_to: "none"

workspace:
  - apps/mcu
  - modules/converter
  - packages/core
  - packages/core_storage_base
  - packages/core_storage_isar
  - packages/icons
  - packages/l10n
  - packages/mobile_ads
  - packages/mobile_ads_google
  - packages/platform_utils
  - packages/utils

environment:
  sdk: ^3.12.0

dev_dependencies:
  lints: ^6.0.0
