name: core_storage_base
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: "flutter"

  core:
    path: ../core
  platform_utils:
    path: ../platform_utils
  utils:
    path: ../utils

