name: platform_utils
publish_to: "none"

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  ffmpeg_kit_flutter_new: ^4.6.2-full-gpl
  audioplayers: ^6.8.1
  flutter_local_notifications: ^22.3.0
  flutter_foreground_task: ^11.0.1

  mime: ^2.1.0
  path: ^1.9.1
  path_provider: ^2.1.6
  file_picker: 12.0.0
  file_picker_platform_interface: 3.1.0
  universal_io: ^2.3.1
  url_launcher: ^6.3.2
  share_plus: ^13.3.0
  permission_handler: ^12.0.1

  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
