name: platform_utils
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  workmanager: ^0.6.0
  ffmpeg_kit_flutter_new: ^3.1.0-full-gpl

  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  universal_file: ^1.0.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
