name: mobile_ads
publish_to: "none"

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: "flutter"

  core:
    path: ../core
  platform_utils:
    path: ../platform_utils
  utils:
    path: ../utils

